### ISSUE TITLE
Live testing

### ISSUE THREAD

**Issue by jbpenrath** [openfun/verna#56]
Hardtest verna to catch remaining errors.

**Comment by carofun** [comment]
### can't see choices of multiple choice
<img width="1029" alt="Capture d’écran 2022-10-26 à 10 07 19" src="https://user-images.githubusercontent.com/76939263/197970440-850b144e-1d8e-49d6-bb42-2571031ef0d6.png">

**Comment by carofun** [comment]
### blank page on saving

Clicking on save sends us to a blank page. Are the buttons supposed to be displayed here ?

<img width="949" alt="Capture d’écran 2022-10-26 à 10 01 55" src="https://user-images.githubusercontent.com/76939263/197970723-af36ac6b-bc10-4f01-8d5e-c81bcfa98088.png">

**Comment by Kitero** [comment]
> 

Fixed in last fixup

**Comment by jbpenrath** [comment]
There is a z-index issue on the tooltip of the toolbar.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/9265241/199950401-84f487d5-f07d-4e1e-ba8a-eb159addafd5.png">

**Comment by jbpenrath** [comment]
What do you think to put Language and Editor selects within the header.
![](https://files.slack.com/files-pri/T029LTMLG-F049AKLFZ46/image.png)

**Comment by jbpenrath** [comment]
I do not understand `Scrolling Menu` widget purpose. I think `Single choice question`

**Comment by jbpenrath** [comment]
The layout when translation does not exist is broken.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/9265241/199954836-ecb8b57d-2a40-4c16-8111-a28d75c24efd.png">

**Comment by NathanVss** [comment]
**Crash when answering a second time with no choices selected.**

- The crash still occurs after page refresh.

https://user-images.githubusercontent.com/9628870/200281914-7dad1cf6-40a7-4bb2-9a66-7c6c6153df39.mov

**Comment by NathanVss** [comment]
**Crash when trying to submit empty number answer.**

During this video I:
- CMD + A to select the whole input content
- Press Delete
- Submit the form


https://user-images.githubusercontent.com/9628870/200287140-fed7c863-6c34-4aa6-ae16-294fe1b91908.mov

**Comment by NathanVss** [comment]
**I can't use the keyboard's delete key to remove the input number content**


https://user-images.githubusercontent.com/9628870/200287560-f4db2ea0-511d-45a1-86da-bfed7316e8ef.mov

**Comment by NathanVss** [comment]
**The first `unchecked` answer is not took into account until I answer a `checked` value.**


https://user-images.githubusercontent.com/9628870/200288243-5c90c20d-f3ba-4782-a092-e629b9b97de2.mov

**Comment by NathanVss** [comment]
Improvement idea: Make re-ordering the multi-choices drag'n'droppable. ( With the same UI/UX as the left sidebar to choose questions ) 

<img width="896" alt="Capture d’écran 2022-11-07 à 11 31 31" src="https://user-images.githubusercontent.com/9628870/200288923-1e7793ff-c41c-49b3-8a75-1e6f715b1567.png">

**Comment by NathanVss** [comment]
**The answer is not took into account**

As you can see on the video the answers count stays 14 even if I select a value the second time. 

NB: It does not happens every time.
NB2: I recorded the video after a page refresh.
NB3: The count stays 14 even after a page refresh.

https://user-images.githubusercontent.com/9628870/200290108-9ee90ed6-715f-49c0-b6c3-004786aa40f0.mov

**Comment by NathanVss** [comment]
**Number input triggers `A component is changing an uncontrolled input to be controlled.` when typing the reply**

<img width="1551" alt="Capture d’écran 2022-11-07 à 11 42 18" src="https://user-images.githubusercontent.com/9628870/200290863-4cc6f06f-f53e-47d9-8996-c0b504608591.png">

**Comment by Kitero** [comment]
> What do you think to put Language and Editor selects within the header. <img alt="image" width="1681" src="https://user-images.githubusercontent.com/9265241/199951741-a2bf4882-095c-424e-9889-39d6805f6a41.png">
Where it's not supposed to be in the real use case, I would keep it separated, but maybe we can put it closer in a third "dev" box on the right?

**Comment by Kitero** [comment]
> The layout when translation does not exist is broken. <img alt="image" width="938" src="https://user-images.githubusercontent.com/9265241/199954836-ecb8b57d-2a40-4c16-8111-a28d75c24efd.png">
> ## Steps to reproduce
> 
>     * Switch to language `fr-CA`


I fixed this behaviour by merging every time the default locale translations in the translation messages of React Intl so it's always filled with the native language translations

**Comment by Kitero** [comment]
> Improvement idea: Make re-ordering the multi-choices drag'n'droppable. ( With the same UI/UX as the left sidebar to choose questions )
> 
> <img alt="Capture d’écran 2022-11-07 à 11 31 31" width="896" src="https://user-images.githubusercontent.com/9628870/200288923-1e7793ff-c41c-49b3-8a75-1e6f715b1567.png">

This is a part that indeed needs to be improved, but it needs changes in the library.

**Comment by Kitero** [comment]
New bug:

Once a whole question translations are set in english
If you try to add the translation in french, the "items" values will override the english ones too

**Comment by jbpenrath** [comment]
There is a glitch on page load. When the sidebar is hidden, it appears then hide. I think we should not display at all the sidebar according to the application state.

![2022-11-22 12 20 27](https://user-images.githubusercontent.com/9265241/203302354-1dd99a64-2199-4245-834d-53167b754988.gif)

**Comment by jbpenrath** [comment]
## Issues with language poll

### Steps to reproduce

1. As editor, edit **language** poll
2. About **Native Language** input, click on Edit button  
3. Modify some options labels
4. Click on Submit button
5. Switch to another language 
6. Repeat steps 2 to 4
7. Go back to the previous language
8. Note that options label corresponds to those sets in the previous language

### Notes
This only concerns this poll. If I create a new poll and add a new "Scrolling menu" widget, all is working fine.

### Screenshots
![poll-language-issue](https://user-images.githubusercontent.com/9265241/203330463-8f81b152-715c-420c-8c6a-07a4ba77a426.jpg)
